language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: brycefarrell-github
    token:
      secure: 72635b563a81348891f6f21c5de30d79cd41e67c
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'